CREATE TABLE IF NOT EXISTS ChatPing (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(64) NOT NULL,
    user_id VARCHAR(64),
    group_id VARCHAR(64),
    is_user BOOLEAN,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
